// Generated by gencpp from file randomwalker/GetBoundsRequest.msg
// DO NOT EDIT!


#ifndef RANDOMWALKER_MESSAGE_GETBOUNDSREQUEST_H
#define RANDOMWALKER_MESSAGE_GETBOUNDSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace randomwalker
{
template <class ContainerAllocator>
struct GetBoundsRequest_
{
  typedef GetBoundsRequest_<ContainerAllocator> Type;

  GetBoundsRequest_()
    {
    }
  GetBoundsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::randomwalker::GetBoundsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::randomwalker::GetBoundsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetBoundsRequest_

typedef ::randomwalker::GetBoundsRequest_<std::allocator<void> > GetBoundsRequest;

typedef boost::shared_ptr< ::randomwalker::GetBoundsRequest > GetBoundsRequestPtr;
typedef boost::shared_ptr< ::randomwalker::GetBoundsRequest const> GetBoundsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::randomwalker::GetBoundsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::randomwalker::GetBoundsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace randomwalker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::randomwalker::GetBoundsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::randomwalker::GetBoundsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::randomwalker::GetBoundsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::randomwalker::GetBoundsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::randomwalker::GetBoundsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::randomwalker::GetBoundsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::randomwalker::GetBoundsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::randomwalker::GetBoundsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::randomwalker::GetBoundsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "randomwalker/GetBoundsRequest";
  }

  static const char* value(const ::randomwalker::GetBoundsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::randomwalker::GetBoundsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::randomwalker::GetBoundsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::randomwalker::GetBoundsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetBoundsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::randomwalker::GetBoundsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::randomwalker::GetBoundsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RANDOMWALKER_MESSAGE_GETBOUNDSREQUEST_H
