// Generated by gencpp from file randomwalker/GetBounds.msg
// DO NOT EDIT!


#ifndef RANDOMWALKER_MESSAGE_GETBOUNDS_H
#define RANDOMWALKER_MESSAGE_GETBOUNDS_H

#include <ros/service_traits.h>


#include <randomwalker/GetBoundsRequest.h>
#include <randomwalker/GetBoundsResponse.h>


namespace randomwalker
{

struct GetBounds
{

typedef GetBoundsRequest Request;
typedef GetBoundsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetBounds
} // namespace randomwalker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::randomwalker::GetBounds > {
  static const char* value()
  {
    return "b43c3f7151561a46ea4332c06c9db277";
  }

  static const char* value(const ::randomwalker::GetBounds&) { return value(); }
};

template<>
struct DataType< ::randomwalker::GetBounds > {
  static const char* value()
  {
    return "randomwalker/GetBounds";
  }

  static const char* value(const ::randomwalker::GetBounds&) { return value(); }
};


// service_traits::MD5Sum< ::randomwalker::GetBoundsRequest> should match 
// service_traits::MD5Sum< ::randomwalker::GetBounds > 
template<>
struct MD5Sum< ::randomwalker::GetBoundsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::randomwalker::GetBounds >::value();
  }
  static const char* value(const ::randomwalker::GetBoundsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::randomwalker::GetBoundsRequest> should match 
// service_traits::DataType< ::randomwalker::GetBounds > 
template<>
struct DataType< ::randomwalker::GetBoundsRequest>
{
  static const char* value()
  {
    return DataType< ::randomwalker::GetBounds >::value();
  }
  static const char* value(const ::randomwalker::GetBoundsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::randomwalker::GetBoundsResponse> should match 
// service_traits::MD5Sum< ::randomwalker::GetBounds > 
template<>
struct MD5Sum< ::randomwalker::GetBoundsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::randomwalker::GetBounds >::value();
  }
  static const char* value(const ::randomwalker::GetBoundsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::randomwalker::GetBoundsResponse> should match 
// service_traits::DataType< ::randomwalker::GetBounds > 
template<>
struct DataType< ::randomwalker::GetBoundsResponse>
{
  static const char* value()
  {
    return DataType< ::randomwalker::GetBounds >::value();
  }
  static const char* value(const ::randomwalker::GetBoundsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RANDOMWALKER_MESSAGE_GETBOUNDS_H
