// Generated by gencpp from file randomwalker/GetScoreResponse.msg
// DO NOT EDIT!


#ifndef RANDOMWALKER_MESSAGE_GETSCORERESPONSE_H
#define RANDOMWALKER_MESSAGE_GETSCORERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace randomwalker
{
template <class ContainerAllocator>
struct GetScoreResponse_
{
  typedef GetScoreResponse_<ContainerAllocator> Type;

  GetScoreResponse_()
    : score(0)  {
    }
  GetScoreResponse_(const ContainerAllocator& _alloc)
    : score(0)  {
  (void)_alloc;
    }



   typedef int32_t _score_type;
  _score_type score;




  typedef boost::shared_ptr< ::randomwalker::GetScoreResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::randomwalker::GetScoreResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetScoreResponse_

typedef ::randomwalker::GetScoreResponse_<std::allocator<void> > GetScoreResponse;

typedef boost::shared_ptr< ::randomwalker::GetScoreResponse > GetScoreResponsePtr;
typedef boost::shared_ptr< ::randomwalker::GetScoreResponse const> GetScoreResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::randomwalker::GetScoreResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::randomwalker::GetScoreResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace randomwalker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::randomwalker::GetScoreResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::randomwalker::GetScoreResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::randomwalker::GetScoreResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::randomwalker::GetScoreResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::randomwalker::GetScoreResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::randomwalker::GetScoreResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::randomwalker::GetScoreResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ed963831938da1fc8151b77dec7741f";
  }

  static const char* value(const ::randomwalker::GetScoreResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ed963831938da1fULL;
  static const uint64_t static_value2 = 0xc8151b77dec7741fULL;
};

template<class ContainerAllocator>
struct DataType< ::randomwalker::GetScoreResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "randomwalker/GetScoreResponse";
  }

  static const char* value(const ::randomwalker::GetScoreResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::randomwalker::GetScoreResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 score\n\
\n\
";
  }

  static const char* value(const ::randomwalker::GetScoreResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::randomwalker::GetScoreResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetScoreResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::randomwalker::GetScoreResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::randomwalker::GetScoreResponse_<ContainerAllocator>& v)
  {
    s << indent << "score: ";
    Printer<int32_t>::stream(s, indent + "  ", v.score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RANDOMWALKER_MESSAGE_GETSCORERESPONSE_H
