(cl:defpackage randomwalker-srv
  (:use )
  (:export
   "GETBOUNDS"
   "<GETBOUNDS-REQUEST>"
   "GETBOUNDS-REQUEST"
   "<GETBOUNDS-RESPONSE>"
   "GETBOUNDS-RESPONSE"
   "GETSCORE"
   "<GETSCORE-REQUEST>"
   "GETSCORE-REQUEST"
   "<GETSCORE-RESPONSE>"
   "GETSCORE-RESPONSE"
  ))

